  
project:
  title: "Project name"
  type: cohabys
  output-dir: public 

## Customising formats
format:
  cohabys-html: default
  typst-cohabys: default
  cohabys-docx: default
  
###########
##### To choose your project format : go to _extensions/cohabys and comment/uncomment your choice
##### By default, no project features are enabled
###########



 # If type: website
website:
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - text: "Source"
        icon: git
        href: https://github.com/leolea12/quarto-cohabys-extension
      - text: "Documentation"
        icon: book
        href: https://quarto.org


# If type: book
book:
  title: "Title"
  author: "Author"
  date: today
  sidebar: 
        contents: auto
  chapters:
    - index.qmd
